### ISSUE TITLE
UX Review

### ISSUE THREAD

**Issue by JoshData** [18F/2015-foia-hub#797]
Hi all,

Congrats on making it this far with the project. Here are assorted thoughts from going through the site.
### Homepage

What's the purpose of this website? To "open" FOIA is not a helpful answer. The name of the website (openFOIA) doesn't match what the project actually does. (openFOIA is a fine internal name for the project and a fine placeholder for a public name, if that's what it is.)

The blue underlines under your H1's (on the homepage that's "Begin your federal") is, to me, completely blinding. I have extreme difficulty reading all of the multi-line H1s throughout the site.

The agency autocomplete is very nice.
### Agency Pages

I went to a few random agency pages.

On [this one](https://open.foia.gov/contacts/united-states-international-boundary-and-water-com), there's a character encoding issue in the agency description (the question mark).

I'm not sure what the page is supposed to help me with, and the positions of the elements of the page doesn't seem to have any logic to it. A natural linear structure would be by the chronology of a request:
- Before-you-submit info on top. (Why is this rendered differently than other parts of the page?)
- Contact information for submitting. (ps, why is "FAX" in all caps?)
- How long to wait before I should contact the agency (median waiting times).
- How to contact the agency when it's taking too long.

Some steps are confusing because of the presentation of semi-redundant information: multiple submission methods and multiple contact points. Options without explanation are confusing.
- Does it matter if I choose online, email, FAX, or mail? It would help to prioritize the options. Like, if I'm using openFOIA, it is very unlikely I'm going to go find a FAX machine and use that method. If email exists, maybe that's a preferable option (to all parties) than postal mail. And if an online request form is available, maybe that's the best option of all (for the agency at least)? Better to present one recommended option than possibly four (or more?) methods that the user has no way to choose between.
- How should I choose which contact method to use if I "Have questions?"? On [this page](https://open.foia.gov/contacts/united-states-international-boundary-and-water-com) (same link as above), there are two contacts listed --- but they have the same contact information. So the user first has to contend with a choice, and then it turns out the user didn't actually have a choice to begin with. This was also true on [the other random agency](https://open.foia.gov/contacts/committee-for-purchase-from-people-who-are-blind-o/) I looked at.
- There are two links on the page to the agency's FOIA website.

**Comment by khandelwal** [comment]
@JoshData Thanks for all the useful feedback. I split these into separate issues to make them easier to think about. 

I really appreciate all the effort you clearly spent on going through the site.

**Comment by nsinai** [comment]
Thanks for the feedback @JoshData
