### ISSUE TITLE
PR Campaign

### ISSUE THREAD

**Issue by NDuma** [18F/2015-foia-hub#839]
Start PR Campaign
 - [ ] Initiate CrowdFunding / Grant / 'Creative' Funding Matrix
 - - PatreoKicFlower?
 - [ ] Isolate Decision(s) & Create Requests & Ads
 - [ ] Developer Community Requests for participation (FCC)
 - [ ] Can GitHubpages.eyeOH host this - Something Else? Funding Requests / (screech! Ads?)
 - [ ] Find Relevant Media Articles / Contact Writers & Editors etc...

Is there some sort of Gant / Burn down / Project Chart?
114 issues...

(Mail extension / progress monitor / information donation portal?)

-- Edit:
I've found the others listed on [Platforms](https://github.com/18F/2015-foia/wiki/Platforms) etc... assuming this is why this stalled out?

**Comment by pkarman** [comment]
This project is no longer active.
